### ISSUE TITLE
The Library depends on a changed dev-master of SwissPaymentSlipPdf

### ISSUE THREAD

**Issue by ravage84** [ravage84/SwissPaymentSlipFpdf#1]
The underlying libraries SwissPaymentSlipPdf and SwissPaymentSlip respecively have some API changes. Thus, neither the examples nor the SwissPaymentSlipFpdf class itself do work anyore.

A new release needs to be created which is adjusted to the changes in SwissPaymentSlipPdf and SwissPaymentSlip respecively.
Also the libary should not depend on a dev-master but a Git tag.

**Comment by ravage84** [comment]
One of the underlying, API breaking changes was the renaming of the classes:
https://github.com/ravage84/SwissPaymentSlipPdf/commit/5ca45afe1a10f4df56378f897b9930a238b5963d#commitcomment-9749927

**Comment by zu** [comment]
Just for your information: The OCR-B font is also available as webfont at http://www.fonts.com/font/linotype/ocr-b?QueryFontType=Web#buying-options
But of course it costs here as well. But there is a free option with a max af  25,000 pageviews per month.
This might be good enough to start ;-)

But I'm not sure if this fits in either SwissPaymentSlip implementations.

**Comment by ravage84** [comment]
@zu thanks for your input. Again, downloading a copy of it, is not a problem, but the legal (license) question still prevails.
When I find time, I really should get in touch with someone from **Die Post** to clear this up.

And @zu no this offer does not fit into an implementation of the SwissPaymentSlip library because we need to have a copy of the font only once, convert it to a TCPDF/FPDF compatible format and then we can use this locally. We don't need to serve it a s a web font

**Comment by ravage84** [comment]
Resolved with the release of https://github.com/ravage84/SwissPaymentSlipFpdf/releases/tag/0.6.0

Thank you all for your patience.
