### ISSUE TITLE
Issue with Cents

### ISSUE THREAD

**Issue by FFDani** [ravage84/SwissPaymentSlipFpdf#7]
When you set a number with a 0 after the decimal point, for example 1.05, as the amount on the payment slip, it is displayed as 1.50. The reason is because the str_pad in the function getAmountCents() sets the 0 after the 5 and not before. I put a patch file in the zip that i attached here with the fix to this issue

[Changes.zip](https://github.com/ravage84/SwissPaymentSlipFpdf/files/146758/Changes.zip)

**Comment by ravage84** [comment]
@FFDani thanks for the report.

Could you create a Pull Request with the changes included?
At best would be if you could also add a test to cover this case so we don't get a regression in the future.

By the way the correct repository for this would be https://github.com/ravage84/SwissPaymentSlip/

**Comment by ravage84** [comment]
Closing as PR https://github.com/ravage84/SwissPaymentSlip/pull/21 is provided.
