### ISSUE TITLE
Unable to print German character in FPDF

### ISSUE THREAD

**Issue by teamjhuns2014** [ravage84/SwissPaymentSlipFpdf#8]
Hi There,

I am trying to generate Payment Slip from Vtiger and using this module. But somehow the german characters r not getting displayed in payment slip. Can nyone guide please.

AJ

**Comment by ravage84** [comment]
Hi,

I guess your problem is less FPDF or my library but some encoding problem of your application.
If you want, you can Skype chat me (I speak German and English).

**Comment by teamjhuns2014** [comment]
Hi Thr,

Thanks for reverting. whts your skype id ? 

I am on Jhuns.Infotech

AJ

**Comment by ravage84** [comment]
Closing as @teamjhuns2014 did not use the FPDF library.
