### ISSUE TITLE
automatic word wrapping

### ISSUE THREAD

**Issue by ictparkjan** [ravage84/SwissPaymentSlipFpdf#9]
Would be very nice if there would be a automatic word wrapping, because the payer field at the 	"acknowledgement of acceptance" (left side) is much smaller than the same field in the main area (right side)
![06-04-_2017_12-16-44](https://cloud.githubusercontent.com/assets/13939572/24749365/12386782-1ac3-11e7-9c8a-693e31c9f547.png)
.

**Comment by ravage84** [comment]
This needs to be implemented in [ravage84/SwissPaymentSlip](https://github.com/ravage84/SwissPaymentSlip). I've opened [an issue](ravage84/SwissPaymentSlip/issues/29) there.

**Comment by ravage84** [comment]
Thanks for the suggestion. If you want to help implementing this, please let's continue in the new issue.
